"""Activity spans: when an agent was actually working in a session.

A *turn* starts with a human input (a typed prompt, a slash command the person typed, or the
person's answer to a question the agent asked) and lasts until the agent's last output before
the next human input. Anything else that reaches the agent in between (an injected notification,
a system reminder, a compaction summary, a command's caveat or output) continues the current
turn instead of starting one. Inside a turn, a silence of `SEGMENT_GAP_SECONDS` or more ends the
activity there; records after it are a new *segment* of the same turn, so idle hours aren't
counted. Segments, and the runs of a session's sub-agents, are joined into *blocks* when they are
less than the gap setting apart. This module holds that arithmetic, the cache of per-transcript
turns, and the Claude Code transcript reader; the Codex and OpenCode readers live next to their
own parsing (`agents/codex/rollout.py`, `agents/opencode/scan.py`).
"""

import json
import os
import re
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

from . import detail

DEFAULT_GAP_SECONDS = 30 * 60
# Within a turn, a silence this long ends the turn (the cache is independent of `--gap-minutes`).
SEGMENT_GAP_SECONDS = 30 * 60
MIN_SPAN_SECONDS = 60.0
# A last turn whose final record is this recent is taken to still be running: it ends "now".
LIVE_WINDOW_SECONDS = 120.0
# Bumped whenever how turns are read changes: a cached entry of another version is recomputed.
ACTIVITY_VERSION = 7
# How much of the agent's last answer is kept per turn (and per block, as `final`).
REPLY_CHARS = 400
# How much of a turn's prompt is kept (in the cache and in `json activity`).
PROMPT_CHARS = 200
# What started a turn: a typed prompt, or the person's answer to a question the agent asked.
# `resume` (activity with no human input before it) and `subagent` (a run of a sub-agent's own
# transcript) are not turns a person started: they count as work but are not listed.
KIND_PROMPT, KIND_ANSWER, KIND_RESUME, KIND_SUBAGENT = 'prompt', 'answer', 'resume', 'subagent'
LISTED_KINDS = (KIND_PROMPT, KIND_ANSWER)

_TS_RE = re.compile(rb'"timestamp":"(\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?)Z"')
# Claude Code user lines that are slash-command scaffolding (the caveat before a command, the
# command's output): they are neither a prompt nor the agent working, so they are skipped
# entirely and can't start, extend, or resume a turn.
_NOISE_PREFIXES = (
    '<local-command-stdout>',
    '<local-command-caveat>',
    'Caveat: The messages below were generated by the user',
)
# Other user lines with text that aren't a prompt reaching the agent (they still count as activity).
_NOT_A_TURN_PREFIXES = (
    '[Request interrupted',
    'This session is being continued from a previous conversation',
)


class TurnBuilder:
    """Feeds on events in transcript order and yields turns
    `[start, end, prompt, kind, reply, segments]`. A prompt (human input) starts a turn; activity
    extends the current turn's last segment, or opens a new segment when it comes
    `SEGMENT_GAP_SECONDS` or more after it. Activity before any human input is kept only when
    there is no human input at all."""

    def __init__(self) -> None:
        self.turns: List[list] = []
        self._current: Optional[list] = None
        self._pre: Optional[list] = None     # a `resume` pseudo-turn for activity before any prompt

    def prompt(self, t: float, text: str = '', kind: str = KIND_PROMPT) -> None:
        self._current = [t, t, text[:PROMPT_CHARS], kind, '', [[t, t]]]
        self.turns.append(self._current)

    @staticmethod
    def _extend(turn: list, t: float) -> None:
        seg = turn[5][-1]
        if t - seg[1] >= SEGMENT_GAP_SECONDS:
            turn[5].append([t, t])
        elif t > seg[1]:
            seg[1] = t
        turn[1] = max(turn[1], t)

    def activity(self, t: float) -> None:
        if self._current is not None:
            self._extend(self._current, t)
        elif self._pre is None:
            self._pre = [t, t, '', KIND_RESUME, '', [[t, t]]]
        else:
            self._extend(self._pre, t)

    def reply(self, text) -> None:
        """The agent's latest answer in the current turn (the last one set wins)."""
        if self._current is not None:
            self._current[4] = text

    def finish(self) -> List[list]:
        if self.turns:
            return self.turns
        return [self._pre] if self._pre is not None else []


def _segments(t: list) -> List[list]:
    return t[5] if len(t) > 5 else [[t[0], t[1]]]


def join_turns(turns: List[list], gap: float = DEFAULT_GAP_SECONDS,
               min_len: float = MIN_SPAN_SECONDS) -> List[dict]:
    """Blocks `{start, end, turns: [{start, end, active, prompt, kind, reply}]}`. Every segment
    of every turn (and every sub-agent run) is an interval; intervals less than `gap` apart are
    joined into one block, and a block shorter than `min_len` is extended to `min_len` so a
    one-message turn stays visible. A block lists the human turns that have a segment in it, with
    the part of the turn inside the block (`start`/`end`, and `active`: seconds of work in it);
    turns nobody started (sub-agent runs, activity before any input) count but are not listed."""
    items = sorted((s, e, i) for i, t in enumerate(turns) for s, e in _segments(t))
    blocks: List[dict] = []
    cur: Optional[dict] = None
    for s, e, i in items:
        if cur is not None and s - cur['end'] < gap:
            cur['end'] = max(cur['end'], e)
        else:
            cur = {'start': s, 'end': e, 'segs': {}}
            blocks.append(cur)
        cur['segs'].setdefault(i, []).append((s, e))
    out: List[dict] = []
    for blk in blocks:
        listed = []
        for i, segs in sorted(blk['segs'].items(), key=lambda kv: kv[1][0][0]):
            t = turns[i]
            if t[3] in LISTED_KINDS:
                listed.append({'start': segs[0][0], 'end': max(e for _s, e in segs),
                               'active': sum(e - s for s, e in segs),
                               'prompt': t[2], 'kind': t[3], 'reply': t[4] if len(t) > 4 else ''})
        end = blk['end']
        if end - blk['start'] < min_len:
            end = blk['start'] + min_len
        out.append({'start': blk['start'], 'end': end, 'turns': listed})
    return out


def raw_runs(turns: List[list], start: float, end: float) -> Tuple[List[dict], List[dict]]:
    """The building blocks `join_turns` works from, without any joining or stretching: the runs
    (each segment of each turn, and each sub-agent run) that fall inside `[start, end)`, and the
    turns they belong to. A run is `{start, end, turn}` where `turn` is the owning turn's start
    (a key into the turns list), or `None` for a sub-agent run; a turn is `{start, end, prompt,
    kind, reply}` (every kind, including the unlisted `resume`; the reader decides what to list).
    A run that crosses the range's edge is returned whole, so a reader can join it exactly as
    `join_turns` would."""
    turns_out: List[dict] = []
    runs: List[dict] = []
    for t in sorted(turns, key=lambda x: x[0]):
        mine = [(a, b) for a, b in _segments(t) if (b > start or (a == b and a >= start)) and a < end]
        if not mine:
            continue
        sub = t[3] == KIND_SUBAGENT
        if not sub:
            turns_out.append({'start': t[0], 'end': t[1], 'prompt': t[2], 'kind': t[3],
                              'reply': t[4] if len(t) > 4 else ''})
        runs.extend({'start': a, 'end': b, 'turn': None if sub else t[0]} for a, b in mine)
    return turns_out, runs


def extend_if_live(turns: List[list], now: float,
                   window: float = LIVE_WINDOW_SECONDS) -> List[list]:
    """The turn that is still running (its last record is within `window` of `now`) ends now."""
    if not turns:
        return turns
    last = max(range(len(turns)), key=lambda i: turns[i][1])
    if 0 <= now - turns[last][1] < window:
        turns = [list(t) for t in turns]
        t = turns[last]
        t[1] = now
        if len(t) > 5:
            t[5] = [list(seg) for seg in t[5]]
            t[5][-1][1] = now
    return turns


def clip_spans(blocks: List[dict], start: float, end: float) -> List[dict]:
    """The parts of `blocks` inside `[start, end)`; empty ones are dropped. A clipped block
    keeps the turns that touch what is left of it, with their true times."""
    out = []
    for blk in blocks:
        a, b = max(blk['start'], start), min(blk['end'], end)
        if b > a:
            turns = [t for t in blk['turns'] if t['end'] > a and t['start'] < b]
            out.append({'start': a, 'end': b, 'turns': turns})
    return out


def parse_utc(value: str) -> Optional[float]:
    fmt = '%Y-%m-%dT%H:%M:%S.%f' if '.' in value else '%Y-%m-%dT%H:%M:%S'
    try:
        return datetime.strptime(value, fmt).replace(tzinfo=timezone.utc).timestamp()
    except ValueError:
        return None


_COMMAND_NAME_RE = re.compile(r'<command-name>\s*(/?[^<\s]+)\s*</command-name>')
_COMMAND_ARGS_RE = re.compile(r'<command-args>(.*?)</command-args>', re.S)


def _is_noise(rec: dict) -> bool:
    """A slash command's caveat / output line (or any meta line)."""
    if rec.get('isMeta'):
        return True
    raw, _tools = detail._texts_and_tools((rec.get('message') or {}).get('content'))
    return raw.lstrip().startswith(_NOISE_PREFIXES)


def _command_line(raw: str) -> Optional[str]:
    """`/model best` from `<command-name>/model</command-name><command-message>…</command-message>
    <command-args>best</command-args>`, or `None` when `raw` isn't a command line."""
    m = _COMMAND_NAME_RE.search(raw)
    if not m:
        return None
    args = _COMMAND_ARGS_RE.search(raw)
    return ' '.join(((m.group(1) if m.group(1).startswith('/') else '/' + m.group(1)) + ' '
                     + (args.group(1).strip() if args else '')).split())


def _answers_of(rec: dict) -> Optional[str]:
    """The person's answer to an `AskUserQuestion` (a user line whose tool result carries
    `toolUseResult.answers`), joined; `None` when this isn't one."""
    result = rec.get('toolUseResult')
    answers = result.get('answers') if isinstance(result, dict) else None
    if isinstance(answers, dict) and answers:
        text = '; '.join(str(v) for v in answers.values() if str(v).strip())
        return text[:PROMPT_CHARS] if text else None
    content = (rec.get('message') or {}).get('content')
    if isinstance(content, list):
        for b in content:
            body = b.get('content') if isinstance(b, dict) and b.get('type') == 'tool_result' else None
            if isinstance(body, str) and body.startswith('Your questions have been answered'):
                found = re.findall(r'"="((?:[^"\\]|\\.)*)"', body)
                if found:
                    return '; '.join(found)[:PROMPT_CHARS]
    return None


def _turn_start(rec: dict) -> Optional[Tuple[str, str]]:
    """`(text, kind)` for a user line that is the person's own input: what they typed (a slash
    command included), or their answer to a question the agent asked. `None` for everything else,
    which continues the current turn: tool results, meta and sub-agent lines, injected
    notifications and reminders (another session's message, a finished background task), a
    compaction summary, interruptions."""
    if rec.get('isMeta') or rec.get('isSidechain'):
        return None
    answer = _answers_of(rec)
    if answer is not None:
        return answer, KIND_ANSWER
    content = (rec.get('message') or {}).get('content')
    raw, _tools = detail._texts_and_tools(content)
    head = raw.lstrip()
    if not head or head.startswith(_NOT_A_TURN_PREFIXES):
        return None
    command = _command_line(raw)
    if not (command is not None or detail.is_human_prompt(rec, raw)):
        return None
    text = command or detail.clean_text(raw).strip() or head
    return text[:PROMPT_CHARS], KIND_PROMPT


def _assistant_text(line: bytes) -> str:
    """The text of an `assistant` line (its text blocks joined), cleaned and cut to `REPLY_CHARS`."""
    try:
        rec = json.loads(line)
    except ValueError:
        return ''
    raw, _tools = detail._texts_and_tools((rec.get('message') or {}).get('content') if isinstance(rec, dict) else None)
    return detail.clean_text(raw).strip()[:REPLY_CHARS]


def claude_turns(path: str) -> List[list]:
    """Turns of a Claude Code transcript's main thread. Every user and assistant line is
    activity (tool results and sub-agent lines included: the agent was working); a line that
    `_turn_start` accepts (the person's own input) also starts a turn. Each turn keeps the
    agent's last text answer."""
    b = TurnBuilder()
    try:
        f = open(path, 'rb')
    except OSError:
        return []
    with f:
        for line in f:
            if b'"timestamp"' not in line:
                continue
            is_user = b'"type":"user"' in line
            is_assistant = not is_user and b'"type":"assistant"' in line
            if not is_user and not is_assistant:
                continue
            m = _TS_RE.search(line)
            t = parse_utc(m.group(1).decode()) if m else None
            if t is None:
                continue
            # Only user lines that carry text, or a question's answer, can start a turn;
            # other tool-result lines are the bulk of a transcript and are never parsed.
            if is_user and (b'"type":"text"' in line or b'"content":"' in line or b'"answers":' in line):
                try:
                    rec = json.loads(line)
                except ValueError:
                    rec = None
                if isinstance(rec, dict) and _is_noise(rec):
                    continue
                start = _turn_start(rec) if isinstance(rec, dict) else None
                if start:
                    b.prompt(t, start[0], start[1])
                    continue
            b.activity(t)
            # The latest main-thread answer with text is kept as raw bytes, decoded once at the end.
            if is_assistant and b'"type":"text"' in line and b'"isSidechain":true' not in line:
                b.reply(line)
    turns = b.finish()
    for t in turns:
        if isinstance(t[4], bytes):
            t[4] = _assistant_text(t[4])
    return turns


def subagent_files(path: str) -> List[str]:
    """The transcripts of a session's sub-agents (and background agents, teammates): every
    `.jsonl` under the folder named like the session next to `<id>.jsonl`, at any depth."""
    folder = path[:-len('.jsonl')] if path.endswith('.jsonl') else path
    out: List[str] = []
    if os.path.isdir(folder):
        for root, _dirs, files in os.walk(folder):
            out.extend(os.path.join(root, fn) for fn in files if fn.endswith('.jsonl'))
    return sorted(out)


def subagent_runs(path: str) -> List[list]:
    """A sub-agent transcript as runs of work: first to last record, split where two records
    are `SEGMENT_GAP_SECONDS` or more apart."""
    runs: List[list] = []
    try:
        f = open(path, 'rb')
    except OSError:
        return runs
    with f:
        for line in f:
            if b'"timestamp"' not in line:
                continue
            m = _TS_RE.search(line)
            t = parse_utc(m.group(1).decode()) if m else None
            if t is None:
                continue
            if runs and t - runs[-1][1] < SEGMENT_GAP_SECONDS:
                if t > runs[-1][1]:
                    runs[-1][1] = runs[-1][5][0][1] = t
            else:
                runs.append([t, t, '', KIND_SUBAGENT, '', [[t, t]]])
    return runs


def load_cache(path: str) -> Dict[str, dict]:
    from . import cache
    return cache.load(path=path)


def save_cache(c: Dict[str, dict], path: str) -> None:
    from . import cache
    cache.save(c, path=path)


def cached_turns(c: Dict[str, dict], key: str, size: int, mtime: float, compute,
                 trust: bool = True) -> List[list]:
    """The turns for `key` from cache `c` when its (size, mtime, version) still match, else
    `compute()`d and stored. `trust=False` (a file written within the last moments, whose mtime
    can't tell two writes apart) always recomputes."""
    entry = c.get(key)
    if (trust and isinstance(entry, dict) and entry.get('version') == ACTIVITY_VERSION
            and entry.get('size') == size and entry.get('mtime') == mtime):
        return entry.get('turns') or []
    turns = compute()
    c[key] = {'version': ACTIVITY_VERSION, 'size': size, 'mtime': mtime, 'turns': turns}
    return turns
