"""Activity spans: when an agent was actually working in a session.

A *turn* runs from the moment a prompt reaches the agent (a typed prompt, or a notification
that wakes it, e.g. a finished background task) to the last thing the agent recorded before the
next prompt. Consecutive turns whose gap (end of one to the start of the next) is shorter than
the gap setting are joined into one block, so a run of related work reads as one flow. This
module holds the pure turn/span arithmetic, the cache of per-transcript turns, and the Claude
Code transcript reader; the Codex and OpenCode readers live next to their own parsing
(`agents/codex/rollout.py`, `agents/opencode/scan.py`).
"""

import json
import re
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

from . import detail

DEFAULT_GAP_SECONDS = 30 * 60
# Within a turn, a silence this long ends the turn (the cache is independent of `--gap-minutes`).
SEGMENT_GAP_SECONDS = 30 * 60
MIN_SPAN_SECONDS = 60.0
# A last turn whose final record is this recent is taken to still be running: it ends "now".
LIVE_WINDOW_SECONDS = 120.0
# Bumped whenever how turns are read changes: a cached entry of another version is recomputed.
ACTIVITY_VERSION = 3
# How much of a turn's prompt is kept (in the cache and in `json activity`).
PROMPT_CHARS = 200
# What started a turn: a typed prompt, an injected notification that woke the agent, or the
# agent carrying on by itself after a long silence.
KIND_PROMPT, KIND_NOTIFICATION, KIND_RESUME = 'prompt', 'notification', 'resume'

_TS_RE = re.compile(rb'"timestamp":"(\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?)Z"')
# Claude Code user lines that carry text but aren't a prompt reaching the agent.
_NOT_A_TURN_PREFIXES = (
    '<local-command-stdout>',
    '<local-command-caveat>',
    'Caveat: The messages below were generated by the user',
    '[Request interrupted',
    'This session is being continued from a previous conversation',
)


class TurnBuilder:
    """Feeds on events in transcript order and yields turns `[start, end, prompt, kind]`. A
    prompt starts a turn; activity extends the current one, unless it comes
    `SEGMENT_GAP_SECONDS` or more after the turn's last record (the agent resumed on its own,
    e.g. after a compaction or a resumed session), in which case it starts a `resume` turn."""

    def __init__(self) -> None:
        self.turns: List[list] = []
        self._current: Optional[list] = None
        self._pre: List[list] = []    # activity before the first prompt
        self._pre_current: Optional[list] = None

    def prompt(self, t: float, text: str = '', kind: str = KIND_PROMPT) -> None:
        self._current = [t, t, text[:PROMPT_CHARS], kind]
        self.turns.append(self._current)

    def activity(self, t: float) -> None:
        if self._current is not None:
            if t - self._current[1] >= SEGMENT_GAP_SECONDS:
                self.prompt(t, '', KIND_RESUME)
            elif t > self._current[1]:
                self._current[1] = t
        elif self.turns:
            return
        elif self._pre_current is None or t - self._pre_current[1] >= SEGMENT_GAP_SECONDS:
            self._pre_current = [t, t, '', KIND_RESUME]
            self._pre.append(self._pre_current)
        elif t > self._pre_current[1]:
            self._pre_current[1] = t

    def finish(self) -> List[list]:
        """Activity that precedes every prompt only counts when there is no prompt at all."""
        return self.turns if self.turns else self._pre


def _turn_dict(t: list) -> dict:
    return {'start': t[0], 'end': t[1], 'prompt': t[2], 'kind': t[3]}


def join_turns(turns: List[list], gap: float = DEFAULT_GAP_SECONDS,
               min_len: float = MIN_SPAN_SECONDS) -> List[dict]:
    """Blocks `{start, end, turns: [{start, end, prompt, kind}]}`: turns (any order) are joined
    when the next one starts less than `gap` after the previous block's end; a block shorter
    than `min_len` is extended to `min_len` so a one-message turn stays visible (its turns keep
    their true times)."""
    blocks: List[dict] = []
    for t in sorted(turns, key=lambda x: x[0]):
        if blocks and t[0] - blocks[-1]['end'] < gap:
            blocks[-1]['end'] = max(blocks[-1]['end'], t[1])
            blocks[-1]['turns'].append(_turn_dict(t))
        else:
            blocks.append({'start': t[0], 'end': t[1], 'turns': [_turn_dict(t)]})
    for b in blocks:
        if b['end'] - b['start'] < min_len:
            b['end'] = b['start'] + min_len
    return blocks


def extend_if_live(turns: List[list], now: float,
                   window: float = LIVE_WINDOW_SECONDS) -> List[list]:
    """The turn that is still running (its last record is within `window` of `now`) ends now."""
    if not turns:
        return turns
    last = max(range(len(turns)), key=lambda i: turns[i][1])
    if 0 <= now - turns[last][1] < window:
        turns = [list(t) for t in turns]
        turns[last][1] = now
    return turns


def clip_spans(blocks: List[dict], start: float, end: float) -> List[dict]:
    """The parts of `blocks` inside `[start, end)`; empty ones are dropped. A clipped block
    keeps the turns that touch what is left of it, with their true times."""
    out = []
    for blk in blocks:
        a, b = max(blk['start'], start), min(blk['end'], end)
        if b > a:
            turns = [t for t in blk['turns'] if t['end'] > a and t['start'] < b]
            out.append({'start': a, 'end': b, 'turns': turns})
    return out


def parse_utc(value: str) -> Optional[float]:
    fmt = '%Y-%m-%dT%H:%M:%S.%f' if '.' in value else '%Y-%m-%dT%H:%M:%S'
    try:
        return datetime.strptime(value, fmt).replace(tzinfo=timezone.utc).timestamp()
    except ValueError:
        return None


def _turn_start(rec: dict) -> Optional[Tuple[str, str]]:
    """`(prompt text, kind)` for a user line that is a prompt reaching the agent: typed text,
    or an injected notification (a finished background task, another session's message). `None`
    for tool results, meta lines, sub-agent lines, and command output."""
    if rec.get('isMeta') or rec.get('isSidechain'):
        return None
    content = (rec.get('message') or {}).get('content')
    raw, _tools = detail._texts_and_tools(content)
    head = raw.lstrip()
    if not head or head.startswith(_NOT_A_TURN_PREFIXES):
        return None
    human = detail.is_human_prompt(rec, raw) or head.startswith('<command-')
    text = detail.clean_text(raw).strip() or head
    return text[:PROMPT_CHARS], KIND_PROMPT if human else KIND_NOTIFICATION


def claude_turns(path: str) -> List[list]:
    """Turns of a Claude Code transcript. Every user and assistant line is activity (tool
    results and sub-agent work included: the agent was working); a line that `_turn_start`
    accepts also starts a turn."""
    b = TurnBuilder()
    try:
        f = open(path, 'rb')
    except OSError:
        return []
    with f:
        for line in f:
            if b'"timestamp"' not in line:
                continue
            is_user = b'"type":"user"' in line
            if not is_user and b'"type":"assistant"' not in line:
                continue
            m = _TS_RE.search(line)
            t = parse_utc(m.group(1).decode()) if m else None
            if t is None:
                continue
            # Only user lines that carry text can start a turn; tool-result lines are the bulk
            # of a transcript and are never parsed.
            if is_user and (b'"type":"text"' in line or b'"content":"' in line):
                try:
                    rec = json.loads(line)
                except ValueError:
                    rec = None
                start = _turn_start(rec) if isinstance(rec, dict) else None
                if start:
                    b.prompt(t, start[0], start[1])
                    continue
            b.activity(t)
    return b.finish()


def load_cache(path: str) -> Dict[str, dict]:
    from . import cache
    return cache.load(path=path)


def save_cache(c: Dict[str, dict], path: str) -> None:
    from . import cache
    cache.save(c, path=path)


def cached_turns(c: Dict[str, dict], key: str, size: int, mtime: float, compute,
                 trust: bool = True) -> List[list]:
    """The turns for `key` from cache `c` when its (size, mtime, version) still match, else
    `compute()`d and stored. `trust=False` (a file written within the last moments, whose mtime
    can't tell two writes apart) always recomputes."""
    entry = c.get(key)
    if (trust and isinstance(entry, dict) and entry.get('version') == ACTIVITY_VERSION
            and entry.get('size') == size and entry.get('mtime') == mtime):
        return entry.get('turns') or []
    turns = compute()
    c[key] = {'version': ACTIVITY_VERSION, 'size': size, 'mtime': mtime, 'turns': turns}
    return turns
