"""Read the most recent exchange (user instruction / Claude's response) from the end of a transcript."""
import json
import re
from dataclasses import dataclass
from typing import List, Optional

from .scan import TAIL_CHUNK, iter_tail_lines

DETAIL_LIMIT = 1 << 25          # max bytes to scan backward from the end (32 MiB, enough to reach the most recent instruction even in a long transcript)
MAX_CHARS = 1200                # max characters passed to the panel per entry
# Blocks to drop entirely (machine-inserted notices, command output)
_TAG_RE = re.compile(r'[ \t]*<(system-reminder|local-command-stdout|local-command-caveat)>'
                     r'.*?</\1>[ \t]*\n?', re.S)
_BOLD_RE = re.compile(r'\*\*(.+?)\*\*', re.S)
_LONE_TAG_RE = re.compile(r'</?[a-z][a-z0-9-]*(?:\s[^>]*)?>')
_COMMAND_NAME_RE = re.compile(r'<command-name>\s*(/\S+)\s*</command-name>')
# For old transcripts without an `origin` field. Prefixes of user lines that weren't typed by a human
NOT_HUMAN_PREFIXES = (
    'Another Claude session sent a message:',
    'This session is being continued from a previous conversation',
    'The user has opened the note',
    'Caveat: The messages below were generated by the user',
    '[Request interrupted',
    'Monitor event:',
)


@dataclass
class Detail:
    last_user: str = ''         # most recent user instruction
    last_assistant: str = ''    # most recent Claude response (one that has text)
    tools: List[str] = None     # names of tools called in the most recent response
    last_command: Optional[str] = None   # most recent slash command name (no arguments)

    def __post_init__(self):
        if self.tools is None:
            self.tools = []


def clean_text(s: str) -> str:
    """Strip machine-inserted content like <system-reminder> to make the text readable."""
    s = _TAG_RE.sub('', s)
    s = _LONE_TAG_RE.sub('', s)
    s = _BOLD_RE.sub(r'\1', s)      # drop emphasis markers for the panel
    lines = [ln.rstrip() for ln in s.splitlines()]
    out: List[str] = []
    for ln in lines:
        if not ln.strip() and (not out or not out[-1].strip()):
            continue
        out.append(ln)
    text = '\n'.join(out).strip()
    return text[:MAX_CHARS]


def is_human_prompt(rec: dict, raw: str) -> bool:
    """Whether this is an instruction a human typed. Newer transcripts use `origin`;
    older ones are judged by their opening text."""
    origin = rec.get('origin')
    if isinstance(origin, dict) and origin.get('kind'):
        return origin['kind'] == 'human'
    head = raw.lstrip()
    if head.startswith('<'):
        return False
    return not head.startswith(NOT_HUMAN_PREFIXES)


def _texts_and_tools(content):
    """(text, list of tool names). Discards thinking and tool_result blocks."""
    if isinstance(content, str):
        return content, []
    texts, tools = [], []
    if isinstance(content, list):
        for b in content:
            if not isinstance(b, dict):
                continue
            if b.get('type') == 'text' and b.get('text'):
                texts.append(b['text'])
            elif b.get('type') == 'tool_use' and b.get('name'):
                tools.append(b['name'])
    return '\n'.join(texts), tools


def _extract_command(raw_text: str) -> Optional[str]:
    """Extract just the slash command name (no arguments) from `raw_text` (the body
    before it's run through `clean_text`). Uses `<command-name>/xxx</command-name>` if
    present; otherwise, if the `clean_text`-ed body starts with `/`, uses its first
    word. Returns None if neither applies."""
    m = _COMMAND_NAME_RE.search(raw_text)
    if m:
        return m.group(1)
    stripped = clean_text(raw_text).strip()
    if stripped.startswith('/'):
        return stripped.split(None, 1)[0]
    return None


def read_detail(path: str, chunk: int = TAIL_CHUNK, limit: int = DETAIL_LIMIT) -> Detail:
    """Walk backward from the end and collect the most recent user message and Claude
    response (one each), plus one most recent slash command name (`last_command`).
    Even after both `last_user` and `last_assistant` are found, keeps scanning back up
    to `limit` if `last_command` is still missing."""
    d = Detail()
    tools: List[str] = []
    seen: set = set()
    try:
        lines = iter_tail_lines(path, chunk, limit)
    except OSError:
        return d
    for line in lines:
        if b'"type":"user"' not in line and b'"type":"assistant"' not in line:
            continue
        try:
            rec = json.loads(line)
        except ValueError:
            continue
        if not isinstance(rec, dict) or rec.get('isSidechain') or rec.get('isMeta'):
            continue
        kind = rec.get('type')
        text, used = _texts_and_tools((rec.get('message') or {}).get('content'))
        if kind == 'assistant':
            if d.last_assistant:
                continue
            if text.strip():
                d.last_assistant = clean_text(text)
                d.tools = tools          # tools called after the response = what's currently running
            else:
                fresh = [t for t in used if t not in seen]
                seen.update(fresh)
                tools = fresh + tools
        elif kind == 'user':
            if d.last_command is None and text.strip():
                d.last_command = _extract_command(text)
            if not d.last_user and text.strip() and is_human_prompt(rec, text):
                cleaned = clean_text(text)
                if cleaned:
                    d.last_user = cleaned
        if d.last_user and d.last_assistant and d.last_command is not None:
            break
    return d


def read_detail_for(path: Optional[str]) -> Detail:
    return read_detail(path) if path else Detail()
