"""transcript の末尾から、直近のやり取り（ユーザーの指示・Claude の応答）を読む。"""
import json
import re
from dataclasses import dataclass
from typing import List, Optional

from .scan import TAIL_CHUNK, iter_tail_lines

DETAIL_LIMIT = 1 << 25          # 末尾から遡る上限（32 MiB。長い transcript でも直近の指示に届く）
MAX_CHARS = 1200                # パネルに渡す 1 本あたりの上限
# 中身ごと落とすブロック（機械が差し込む注意書き・コマンド出力）
_TAG_RE = re.compile(r'[ \t]*<(system-reminder|local-command-stdout|local-command-caveat)>'
                     r'.*?</\1>[ \t]*\n?', re.S)
_BOLD_RE = re.compile(r'\*\*(.+?)\*\*', re.S)
_LONE_TAG_RE = re.compile(r'</?[a-z][a-z0-9-]*(?:\s[^>]*)?>')
_COMMAND_NAME_RE = re.compile(r'<command-name>\s*(/\S+)\s*</command-name>')
# origin の無い古い transcript 向け。人間が打っていない user 行の出だし
NOT_HUMAN_PREFIXES = (
    'Another Claude session sent a message:',
    'This session is being continued from a previous conversation',
    'The user has opened the note',
    'Caveat: The messages below were generated by the user',
    '[Request interrupted',
    'Monitor event:',
)


@dataclass
class Detail:
    last_user: str = ''         # 直近のユーザーの指示
    last_assistant: str = ''    # 直近の Claude の応答（テキストのあるもの）
    tools: List[str] = None     # 直近の応答で呼んだツール名
    last_command: Optional[str] = None   # 直近のスラッシュコマンド名（引数は含めない）

    def __post_init__(self):
        if self.tools is None:
            self.tools = []


def clean_text(s: str) -> str:
    """<system-reminder> などの機械的な差し込みを落として読める形にする。"""
    s = _TAG_RE.sub('', s)
    s = _LONE_TAG_RE.sub('', s)
    s = _BOLD_RE.sub(r'\1', s)      # パネルでは強調記号を落とす
    lines = [ln.rstrip() for ln in s.splitlines()]
    out: List[str] = []
    for ln in lines:
        if not ln.strip() and (not out or not out[-1].strip()):
            continue
        out.append(ln)
    text = '\n'.join(out).strip()
    return text[:MAX_CHARS]


def is_human_prompt(rec: dict, raw: str) -> bool:
    """人間が打った指示か。新しい transcript は origin、古いものは出だしで見る。"""
    origin = rec.get('origin')
    if isinstance(origin, dict) and origin.get('kind'):
        return origin['kind'] == 'human'
    head = raw.lstrip()
    if head.startswith('<'):
        return False
    return not head.startswith(NOT_HUMAN_PREFIXES)


def _texts_and_tools(content):
    """(テキスト, ツール名リスト)。thinking・tool_result は捨てる。"""
    if isinstance(content, str):
        return content, []
    texts, tools = [], []
    if isinstance(content, list):
        for b in content:
            if not isinstance(b, dict):
                continue
            if b.get('type') == 'text' and b.get('text'):
                texts.append(b['text'])
            elif b.get('type') == 'tool_use' and b.get('name'):
                tools.append(b['name'])
    return '\n'.join(texts), tools


def _extract_command(raw_text: str) -> Optional[str]:
    """`raw_text`（`clean_text` を通す前の本文）からスラッシュコマンド名だけを
    取り出す（引数は含めない）。`<command-name>/xxx</command-name>` があれば
    それを、無ければ `clean_text` した本文が `/` で始まるときの先頭の語を使う。
    どちらも無ければ None。"""
    m = _COMMAND_NAME_RE.search(raw_text)
    if m:
        return m.group(1)
    stripped = clean_text(raw_text).strip()
    if stripped.startswith('/'):
        return stripped.split(None, 1)[0]
    return None


def read_detail(path: str, chunk: int = TAIL_CHUNK, limit: int = DETAIL_LIMIT) -> Detail:
    """末尾から遡って直近のユーザー発言と Claude の応答を 1 本ずつ、直近の
    スラッシュコマンド名（`last_command`）を 1 つ拾う。`last_user`・
    `last_assistant` が両方見つかった後も、`last_command` がまだなら
    `limit` まで遡り続ける。"""
    d = Detail()
    tools: List[str] = []
    seen: set = set()
    try:
        lines = iter_tail_lines(path, chunk, limit)
    except OSError:
        return d
    for line in lines:
        if b'"type":"user"' not in line and b'"type":"assistant"' not in line:
            continue
        try:
            rec = json.loads(line)
        except ValueError:
            continue
        if not isinstance(rec, dict) or rec.get('isSidechain') or rec.get('isMeta'):
            continue
        kind = rec.get('type')
        text, used = _texts_and_tools((rec.get('message') or {}).get('content'))
        if kind == 'assistant':
            if d.last_assistant:
                continue
            if text.strip():
                d.last_assistant = clean_text(text)
                d.tools = tools          # 応答より後に呼んだツール＝いま動いている手
            else:
                fresh = [t for t in used if t not in seen]
                seen.update(fresh)
                tools = fresh + tools
        elif kind == 'user':
            if d.last_command is None and text.strip():
                d.last_command = _extract_command(text)
            if not d.last_user and text.strip() and is_human_prompt(rec, text):
                cleaned = clean_text(text)
                if cleaned:
                    d.last_user = cleaned
        if d.last_user and d.last_assistant and d.last_command is not None:
            break
    return d


def read_detail_for(path: Optional[str]) -> Detail:
    return read_detail(path) if path else Detail()
